### PR TITLE
Hamming exercise example refactoring

### PR DESCRIPTION
**Pull request by joelwallis**
This bug blocks #342. Please check [my comment on #342](https://github.com/exercism/xjavascript/pull/342#issuecomment-296231899) about this bug for more info.

### CODE REVIEW

**Comment by joelwallis** [comment]
@tejasbubane https://www.youtube.com/watch?v=5r06heQ5HsI

**Comment by joelwallis** [comment]
Great!

Now it's just a matter of time to get #342 solved and ready to merge on `master` 😎

**Comment by kotp** [comment]
@exercism/javascript

**Comment by matthewmorgan** [comment]
Nice work!

**Pull request merged**
