### PR TITLE
dibs: I will implement exercise run-length-encoding

### PR DESCRIPTION
**Pull request by yonivy**

### CODE REVIEW

**Comment by matthewmorgan** [comment]
@yonivy Thanks so much for doing this.  You've implemented all the canonical tests, and a nice clean example solution as well.

One request: you're missing a few semicolons, and the "house style" here is to include them everywhere they are normally required.  Can you fix that up, and then I would think we're ready to merge your contribution!

**Comment by yonivy** [comment]
@matthewmorgan no problem. A few semicolons coming right up

**Comment by yonivy** [comment]
@matthewmorgan do we have any "house style" linter config?

**Comment by matthewmorgan** [comment]
@yonivy sadly, no!  This project isn't currently using linting at all.  I think that would be a good addition...know anyone who would be interested? ;) The [ecmascript track](https://github.com/exercism/xecmascript) uses it.

**Comment by matthewmorgan** [comment]
Speaking of house style,  we usually like to have one commit per merged PR.  I should have squashed your commits...my bad. 

Thanks again for your contribution!

**Pull request merged**
