### PR TITLE
Clean up docs for x-api v3

### PR DESCRIPTION
**Pull request by kytrinyx**
We're rewriting the language pages on the site to include the documentation, which can now be served via the API.

It's much cleaner--and it means that the documentation is in the repository for the exercises that it references, which is convenient, since the track-maintainers are the ones who should have access to reviewing and merging it.

This is a direct port of the documentation from the docs repository.

### CODE REVIEW

**Comment by rchavarria** [comment]
Some files are deleted while other are mixed together in a different file. Is that ok? Do all language track have the same `docs` folder structure?

**Comment by kytrinyx** [comment]
The old docs weren't used anywhere, so that's fine. All the languages have the same file structure. We may add some more files (e.g. `HINTS.md`), but for now we are operating with only the following:

- about
- installation
- tests
- resources
- learning

Where resources are generically useful things, and learning is specifically resources that would help people learn the language from scratch.

**Comment by rchavarria** [comment]
Ok, nice to know! Thanks!

I'll let @matthewmorgan to merge it.

**Comment by matthewmorgan** [comment]
@kytrinyx thanks!

**Pull request merged**
