### PR TITLE
substituted underscore for hyphen in all spec files

### PR DESCRIPTION
**Pull request by AbdullahAlger**
Substituted all underscores for hyphens in all spec files. This was discussed on the main Exercism Github page as [issue #2581](https://github.com/exercism/exercism.io/issues/2581).

### CODE REVIEW

**Comment by kytrinyx** [comment]
CI is failing with

```
running tests for: atbash-cipher
cp: cannot stat `atbash-cipher/atbash_cipher-test.spec.js': No such file or directory
make[1]: *** [test-assignment] Error 1
make: *** [test] Error 1
The command "make test" exited with 2.
```

**Comment by AbdullahAlger** [comment]
Thanks. I am working on it at the moment.

**Comment by kytrinyx** [comment]
Ok, cool--sometimes people aren't sure what to look for in the failures from Travis.

**Comment by AbdullahAlger** [comment]
Yeah, this is my first time for that. So, I am just reading error by error. Now I am getting one which is a little odd.

```
running tests for: hello-world
Exception loading: /tmp/hello-world.LMmYpY9vvn/hello-world-test.spec.js
{ [Error: Cannot find module './hello-world'] code: 'MODULE_NOT_FOUND' }
Error: Cannot find module './hello-world'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/tmp/hello-world.LMmYpY9vvn/hello-world-test.spec.js:1:80)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
make[1]: *** [test-assignment] Error 1
make: *** [test] Error 1
```

**Comment by kytrinyx** [comment]
> hello-world-test.spec.js

Shouldn't that be `hello-world.spec.js`?

**Comment by kytrinyx** [comment]
Are you able to run `make test` locally?

**Comment by AbdullahAlger** [comment]
Yes, I can run the tests locally, but the issue is within the `spec.js` files themselves. When I change the spec file from, for example `require('./atbash_cipher');` to `require('./atbash-cipher');` the tests fail, otherwise they pass.

**Comment by kytrinyx** [comment]
Sweet!

Would you mind squashing all the test-related commits? (The .gitignore commit is fine as a stand-alone one).

**Comment by AbdullahAlger** [comment]
I think I squashed all the test commits. I've never done it before, but it's saying that it was successful.

**Comment by kytrinyx** [comment]
There are 7 commits (check out the three tabs at the top of the page).

Here's a quick guide to squashing and pushing back up: http://blog.steveklabnik.com/posts/2012-11-08-how-to-squash-commits-in-a-github-pull-request

You can also do a `git rebase -i HEAD~8`

**Comment by AbdullahAlger** [comment]
Squashed!

**Comment by kytrinyx** [comment]
I've merged this in dcd52bb656bfd833aa3f55bef9bed6dd69edbbbf

I had to do it locally, since the third commit (699a3ca) wasn't passing the tests, so I squashed the fourth commit into it.

**Comment by AbdullahAlger** [comment]
@kytrinyx 
Ok. Well, that was an experience! Thanks for your help.

**Comment by kytrinyx** [comment]
My pleasure, thanks for taking the time to work through all that!

**Pull request closed without merging**
