### PR TITLE
meetup: CHANGE approach away from metaprogramming RE: #35.

### PR DESCRIPTION
**Pull request by ZacharyRSmith**
Addresses #35

### CODE REVIEW

**Comment by kytrinyx** [comment]
This looks good to me, thanks.

I'm curious why you use upper case for the first word in the commit message. I like commit messages to read like imperative sentences, and the upper case word makes the emphasis sound really weird in my head. What led you to this practice?

**Comment by ZacharyRSmith** [comment]
Thanks for the question/comment. Compared to other people's commits I've been seeing, I make lots of commits. Because I make so many commits, I started upper casing keywords to help me find commits. I think that I'll stop making so many commits (or squashing them) and stop upper casing.

**Comment by kytrinyx** [comment]
I make a ton of commits as well, and then I usually squash them before I submit pull requests.

**Comment by ZacharyRSmith** [comment]
Yeah, I think I'll make a ton of commits, continuing my upper case method for my own benefit, then squash them with a regular sounding message. Thanks for the feedback!

**Pull request merged**
