### PR TITLE
Add Diamond: tests and examples

### PR DESCRIPTION
**Pull request by santumahapatra**
Tests and examples for Diamond exercise

### CODE REVIEW

**Comment by rchavarria** [comment]
Yeah! Thanks for adding this new exercise. Awesome!

Recently, a new property has been added to `config.json` file called `exercises`. Would you mind to update your pull request to the more recent version of the source code and add Diamond exercise to the new configuration property?

You may have conflicts with `config.json` file. Let me know if you need help updating your code or leave a comment here for whatever the reason.

Once you add Diamond to `exercises` in `config.json`, this PR will be ready to be merged.

**Comment by santumahapatra** [comment]
@rchavarria I added Diamond to `exercises` in `config.json` in the new property. 

Thanks for the help. Is there anything else before this PR is ready to merge?

**Comment by Roshanjossey** [comment]
@rchavarria: I believe there is an issue in configlet about adding a check to see if new exercises are also added to exercises key in config.json. Are we prioritising that issue? If that issue is resolved, it will be used by all language tracks right?

Also should we update any contribution docs w.r.t this? Not everybody will have context of new specifications right?

**Comment by rchavarria** [comment]
@santumahapatra: That's perfect. Merging...

@Roshanjossey: yep, I know some people are working on migrating different tools (such as `configlet`) to deprecate the use of the property `problems`. And yes, I think it'll be used in all tracks. About updating contribution docs, I love that idea.

**Pull request merged**
