### PR TITLE
TESTS.md: replace angle brackets for better rendering

### PR DESCRIPTION
**Pull request by morrme**
Closes: #353

### CODE REVIEW

**Comment by joelwallis** [comment]
Looks good to me.

The only place where I can see `<` and `>` being used is at `SETUP.md`, which is not rendered on exercism.io, but instead bundled into exercises' `README.md` files:
```
❯ find . -name "*.md" | xargs grep -l "<"
./docs/TESTS.md
./SETUP.md
```
So yeah, since #353 only contemplates the rendering issue in the Rails powered app, seems good to merge.

**Comment by joelwallis** [comment]
@matthewmorgan I can see that you're using [a pattern for commit messages](https://github.com/exercism/xjavascript/commits?author=morrme), where you mostly prepend the issue number to the very first line of the commit message. How exactly do you do it?

**Comment by matthewmorgan** [comment]
@morrme Thanks!

@joelwallis let me ping you in Gitter -- I'm not doing anything special with the commits.

**Comment by morrme** [comment]
@matthewmorgan i'm interested in knowing what you do with the commits as well......

**Comment by matthewmorgan** [comment]
@morrme I just use the 'squash merge' feature in the UI.  GitHub must be adding some information to the commit messages.

In the past I've used the CLI to merge the PR, but it results in the contributor not getting credit in the commit history of `master`, so that's a bummer.

The convention on Exercism repos is to squash so we get one commit per PR.  LMK if you have more questions!

**Comment by morrme** [comment]
@matthewmorgan thanks for the clarification.

**Pull request merged**
