### PR TITLE
Robot Simulator example refactoring

### PR DESCRIPTION
**Pull request by joelwallis**
**Blocks #342**

--

The example for the Robot Simulator exercise [is not passing through unit tests](https://github.com/exercism/xjavascript/pull/342#issuecomment-296450529). The issue was already explained by Matthew [in his comment on #342](https://github.com/exercism/xjavascript/pull/342#issuecomment-296454271). I took the opportunity to make a complete refactoring, using a closure to encapsulate variables that are common to multiple methods or could be kept as singleton instead of an internal variable of an instance method.

The file is now passing all unit tests and nows seems to be easier to read and understand.

### CODE REVIEW

**Comment by matthewmorgan** [comment]
Nice work on the refactoring.  I especially appreciate that some of the names are clearer and that you replaced that chain of `if-else` with a `switch-case` block.

I was feeling like there might even be a less [cyclomatically complex](https://en.wikipedia.org/wiki/Cyclomatic_complexity) way to do that, like maybe with an object...and then I took a look back at my own solution to the problem, where I chose to do:

```javascript
RobotSimulator.prototype.advance = function(){
  var setCoords = {
    'north' : function(){this.coordinates[1]++},
    'south' : function(){this.coordinates[1]--},
    'east' : function(){this.coordinates[0]++},
    'west' : function(){this.coordinates[0]--}
  };
  setCoords[this.bearing].call(this);
};
```

Just thought I'd add that to the conversation.  I think the PR is just great as it is.

**Comment by joelwallis** [comment]
Well, one thing that I just found weird is that, in Robot Simulator, when a robot facing north advances, its Y coordinate is increased. From what I understand of a two-dimension robot which faces north, he's actually "pointing up" on the screen - so, its Y coordinate should be decreasing instead of increasing.

**Comment by joelwallis** [comment]
Well, I'll just create a new issue dedicated to discuss the north/south-related direction thing. :)

**Comment by matthewmorgan** [comment]
I guess that depends on the frame of reference.  Must be whoever came up with this originally decided that 'up' > 'down'.  I think it's the same in all the language tracks I've looked at (which is a small sample to be sure :) )

**Comment by joelwallis** [comment]
Yeah, but in order to take an object up on a 2D dimension you need to decrease the Y coordinate. CSS coordinates is a good example:

```css
#box {
  position: fixed;
  left: 50px;
  top: 50x;

  /* If I would like to move #box ten pixels up: */
  top: 40px;
}

**Comment by matthewmorgan** [comment]
Yeah, I see your point.  Given that we're working in a JavaScript (IE, probably at least some front-end work) context, the choice of y-axis direction is at odds with the programming context.

My assumption, which I never examined until now, has always been that the coordinate system is based on the traditional two-dimensional [X-Y graph like in an algebra class](https://www.khanacademy.org/math/algebra-basics/alg-basics-graphing-lines-and-slope/alg-basics-coordinate-planee/a/points-on-the-coordinate-plane), where the origin is at the center and the first quadrant is positive in both coordinates.

Since the `README.md`, defined in [x-common](https://github.com/exercism/x-common/blob/master/exercises/robot-simulator/description.md), is pretty clear on the orientation, we would need to convince the community that it makes sense to use different conventions for different languages.

Does that make sense?  If you wanted to pursue changing this, I think the first thing to do would be to open an issue in [discussions](https://github.com/exercism/discussions).

**Pull request merged**
