### PR TITLE
[triangle] fixing edgecase of triangle inequality law

### PR DESCRIPTION
**Pull request by schorsch3000**
Hi,
in fact, a triangle with lets say side length 10,10,20 and angles 0,0,180 are quite wired, but are technically triangles.

the law is:
z <= x + y 
not 
z < x + y

### CODE REVIEW

**Comment by kytrinyx** [comment]
Nice catch, thank you!

The build is failing -- I'm not sure if the example file is outdated, or if the test needs to be tweaked:

```
running tests for: triangle
.............F.
Failures:
  1) Triangle edge cases of triangle inequality are in fact legal
   Message:
     Expected function to throw an exception.
   Stacktrace:
     Error: Expected function to throw an exception.
    at null.<anonymous> (/tmp/triangle.OYNg68BRrG/triangle_test.spec.js:72:42)
Finished in 0.013 seconds
15 tests, 15 assertions, 1 failure, 0 skipped
```

**Comment by schorsch3000** [comment]
Oh i missed to negate the check for this test.
weirdly a make && make test run without errors on my machine...

**Comment by kytrinyx** [comment]
Weird, I wonder what's different.

Would you also mind squashing the commits?

**Comment by schorsch3000** [comment]
There you go.

**Comment by kytrinyx** [comment]
Lovely, thank you!

**Pull request merged**
