### PR TITLE
fix `sorted is not defined` error.

### PR DESCRIPTION
**Pull request by GantMan**
for those of us with a bit more strict Javascript compilation.

image

### CODE REVIEW

**Comment by matthewmorgan** [comment]
@GantMan thanks for doing this.  Good argument for getting linting set up for this track...

One minor request: stylistically, all the other array definitions have spaces between the brackets and the values.  Would you mind changing that so we stay consistent?  If you don't have time let me know and I can do it.  Thanks again.

**Comment by GantMan** [comment]
I agree wholeheartedly on the linting.  That would catch most issues nicely.
**RE: Spaces** - I believe I know what you're saying.   I can do that right now.

**Comment by GantMan** [comment]
I believe this is what you wanted.   Please review.

**Comment by rchavarria** [comment]
I think @matthewmorgan refers more to

```
var sorted = { 3 : [ 'Kyle' ], 4 : [ 'Christopher', 'Jennifer' ], 6 : [ 'Kareem' ] };
```

Notice `3 : ['K` and `3 : [ 'K`.

By the way. There is a similar *typo* with whitespace in the line 31. I know it's not your fault, but, because it's a similar change, would you mind to modify it?

Thanks a lot!

**Comment by GantMan** [comment]
Ahh, now I see @rchavarria - Fixed! (line 31 as well).

**Comment by matthewmorgan** [comment]
@GantMan thanks!  one last thing-- when possible, we like to have one commit per PR.  Can you squash the 3 commits to one?  If you don't have time let me know and I can do it.  No problem either way.

**Comment by GantMan** [comment]
sorry for the noise, had to remember how to squash commits.   PR should be good to go!

**Comment by matthewmorgan** [comment]
@GantMan @rchavarria thanks!  Better and better...

**Pull request merged**
