### PR TITLE
Update gigasecond to measure milliseconds not dates

### LINKED ISSUE #49: Name nucleobases, not nucleosides
> The primary nucleobases are cytosine (DNA and RNA), guanine (DNA and RNA), adenine (DNA and RNA), thymine (DNA) and uracil (RNA), abbreviated as C, G, A, T, and U, respectively. Because A, G, C, and T appear in the DNA, these molecules are called DNA-bases; A, G, C, and U are called RNA-bases. - [Wikipedia](http://en.wikipedia.org/wiki/Nucleobase)

In other words, we should rename the values in the RNA transcription problem to reflect the following:

* `cytidine` -> `cytosine`
* `guanosine` -> `guanine`
* `adenosine` -> `adenine`
* `thymidine` -> `thymine`
* `uridine` -> `uracil`

### LINKED ISSUE #64: Update queen attack to use _'s not O's for empty spaces
See the updated [problem description](https://github.com/exercism/x-common/blob/master/queen-attack.md)

### LINKED ISSUE #73: gigasecond: use times (not dates) for inputs and outputs
A duration of a gigasecond should be measured in seconds, not
days.

The `gigasecond` problem has been implemented in a number of languages,
and this issue has been generated for each of these language tracks.
This may already be fixed in this track, if so, please make a note of it
and close the issue.

There has been some discussion about whether or not gigaseconds should
take daylight savings time into account, and the conclusion was "no", since
not all locations observe daylight savings time.

### PR DESCRIPTION
**Pull request by rootulp**

### CODE REVIEW

**Comment by kytrinyx** [comment]
Thanks! In the future, would you mention the commit that closes an issue in the issue itself rather than an unrelated issue? Mentioning an issue from a pull request puts the pull request into the timeline of the issue, and when it's an unrelated change it gets a bit confusing.

The build is failing. What do you get locally when you run ` make test-assignment ASSIGNMENT=gigasecond`?

**Comment by rootulp** [comment]
Thanks for the tip! Is there anyway I can go back and associate those issues with past pull requests?

Also I'm not sure why the build is failing. I get 1 passed test when I run `make test-assignment ASSIGNMENT=gigasecond` locally and all tests passing when I run `make test`. The Travis CI report seems to be off by 1 hour for each test. Any advice on how I can fix this?

**Comment by kytrinyx** [comment]
> Is there anyway I can go back and associate those issues with past pull requests?

Maybe if you mention them in a comment in the relevant PR--not sure. It's no biggie, just a useful thing going forward.

> The Travis CI report seems to be off by 1 hour for each test.

Wow, that's infuriating! I have absolutely no idea how to work around this.

**Comment by rootulp** [comment]
This closes #73

**Comment by kytrinyx** [comment]
Thanks! Wold you mind squashing the commits, please?

**Comment by matthewmorgan** [comment]
@kytrinyx i think this issue is addressed by PR #129 .  We could merge that and close this.

**Comment by kytrinyx** [comment]
Excellent, thanks.

**Pull request closed without merging**
