### PR TITLE
Remove package.json and rely on global jasmine installation

### PR DESCRIPTION
**Pull request by tejasbubane**
I think this file is no longer needed.

@joelwallis forgot to remove it in https://github.com/exercism/xjavascript/pull/342#discussion_r112752492

### CODE REVIEW

**Comment by joelwallis** [comment]
You're right!

But, well, since we'll be using a global installation of Jasmine, it makes sense to remote the `./package.json` file too.

**Comment by tejasbubane** [comment]
It is being used by the [Makefile](https://github.com/exercism/xjavascript/blob/master/Makefile#L18). I guess we should change that too. We will then also need to change the [travis.yml](https://github.com/exercism/xjavascript/blob/master/.travis.yml#L9) to install jasmine first before testing. I will try in this PR itself. Thanks for bringing it up 👍

**Comment by tejasbubane** [comment]
Done! I removed the `package.json` and made `Makefile` and `travis` rely on global `jasmine` installation. 😃

**Comment by matthewmorgan** [comment]
Woohoo!!  Onward and upward.

**Pull request merged**
