### PR TITLE
Removed tabs and deleted two-bucket/example-2.js

### PR DESCRIPTION
**Pull request by ThomasZumsteg**
Squashed into one commit, 
 - Removed the second example from two-bucket
 - Replaced tabs with spaces in two-bucket and crypto-square

Thanks to @matthewmorgan for helping to fix the initial pull request.

### CODE REVIEW

**Comment by matthewmorgan** [comment]
Thanks @ThomasZumsteg !

**Comment by ThomasZumsteg** [comment]
@matthewmorgan Thanks for your feedback on the earlier pull request!

**Comment by matthewmorgan** [comment]
My pleasure, any time.

Next time you do a PR,  if there are modifications, no need to close it and open a new one.  You can make all the changes locally and force push back to your fork, which will update the existing PR.

Let me know if you need more information on that, I'm happy to help.

**Comment by ThomasZumsteg** [comment]
Thanks for the insight, I'll do that next time.

I didn't think of force push. It's backfired on me a few time, and I've generally been advised to avoid it.

**Pull request merged**
