### PR TITLE
grains: Change to use big-integer re: #91.

### PR DESCRIPTION
**Pull request by ZacharyRSmith**
Addresses #91

### CODE REVIEW

**Comment by kytrinyx** [comment]
The reference solution for grains is not passing on CI, would you mind taking a look?

**Comment by ZacharyRSmith** [comment]
Sorry I missed that. I'll try to fix it by Monday

**Comment by ZacharyRSmith** [comment]
Hmm...I don't know what I'm doing.

I saw the following in the CI err output:

    The command "make test" exited with 2.
    $ ./bin/fetch-configlet

I also saw fetch-configlet in the .travis.yml file.

So, I looked at the fetch-configlet file. Which led me to [this](https://github.com/exercism/configlet/releases/tag/v1.0.2).

Where I downloaded the source code, which had a README:

    # Configlet

	This is a tool to help verify that an exercism problem repository is valid and up to date.

	There are three common problems that occur:

	1. The `config.json` might be invalid.
	2. Problems might be implemented (test suite + example solution), but not configured.
	3. Slugs in the configuration might not have a corresponding problem.

	## Usage

	```bash
	$ configlet path/to/problem/repository

But ```configlet``` was not a valid command and a quick Google showed no tool to install.

config.json did not help.

I took a quick gander at Travi CI, but found nothing useful.

I looked at a couple of SOs for why their CI tests failed to find modules...upper-vs-lower case, but that is not my problem.

I wondered if it could not resolve file name because of the "-"...so I changed it to "_" but it still failed.

And now I'm tired of puttering around when someone knowledgeable might could fix in 5 minutes. >.<

**Comment by ZacharyRSmith** [comment]
Am reading https://github.com/exercism/x-api/blob/master/CONTRIBUTING.md...

**Comment by kytrinyx** [comment]
Weird, it sounds like the CI test is looking in the wrong place for the biginteger module. Maybe it's looking relative to where the command is being run from, rather than relative to the test file.

**Comment by ZacharyRSmith** [comment]
Copying the big_integer.js file to the xjavascript folder didn't help.

I'm now thinking the Makefile has something to do with it. It has some language specific config. Part of it:

    EXAMPLE := "example.$(FILEEXT)"
    TSTFILE := "$(ASSIGNMENT)_test.spec.$(FILEEXT)"

I think I need to tell it about the big int module somehow.

**Comment by ZacharyRSmith** [comment]
So, I got it passing, but it's hacky. I added big-integer.js to the xjavascript folder, and have the Makefile cp it to the outdir for each "assignment" (exercise) so that it is available for the grains exercise. But it is also being cp'd to the outdir for irrelevant exercises.

I tried to fix this irrelevant cp'ing by changing the Makefile thus: instead of just ```@cp big-integer.$(FILEEXT) $(OUTDIR)```, I tried code along the lines of (pun definitely intended):

    ifeq ($(ASSIGNMENT), grains)
      @cp $(ASSIGNMENT)/big-integer.$(FILEEXT) $(OUTDIR)
    endif

but, depending on what exactly I tried, I got errors such as unexpected end of file, unexpected word, expecting ")", etc. I tried understanding what's going on by SO and the GNU manual, but it seems I'd need a deeper understanding of make and shell to make progress. But I'd prefer spending my time elsewise, and I think this would be a <5min fix for someone who knows what they're doing. So, I'm submitting as-is. I'd definitely understand if you'd prefer not merging this hacky solution. ( :

**Comment by kytrinyx** [comment]
It works, it goes in. Someone will surely be inspired (read: annoyed enough) to fix it at some point :)

**Comment by kytrinyx** [comment]
Thanks!

**Pull request merged**
