### PR TITLE
Make tests require the solution to export a classy function

### PR DESCRIPTION
**Pull request by rchavarria**
As commented on #128, the first exercises require a similar structure to be exported on user's solutions.

### CODE REVIEW

**Comment by matthewmorgan** [comment]
Looks good.  

However, I noticed something odd when running ```make test```.  It looked like only the un-x-ed out tests are being run by the makefile.

The other thing I noticed is that the tests for ```two-bucket``` are all enabled, so all four tests ran.

I am going to merge this, but it seems like we should create new issues for the makefile and correcting ```two-bucket.spec.js``` so that only the first test is enabled by default.

@rchavarria -- what do you think?

**Comment by matthewmorgan** [comment]
@rchavarria BTW thanks-- this must have been a lot of work!

**Comment by rchavarria** [comment]
@matthewmorgan Totally agree with fixing `two-bucket` and make just the first test enabled.

About `make test` issue -- that's strange. I modified nothing about how tests run. And I noticed nothing. It seems they run ok on Travis CI: https://travis-ci.org/exercism/xjavascript/builds/93075730. I see more than one test on each exercise.

**Comment by matthewmorgan** [comment]
I looked into it and it seems it's a difference in the [OSX implementation](http://stackoverflow.com/questions/2320564/variations-of-sed-between-osx-and-gnu-linux) of ```sed -i``` vs the Linux one.

The ES track uses a different script than the JS track for modifying the test files before evaluation.  This line can be altered to fix it on OSX.

```
-   @sed -i.original 's/\bxit\b/it/g' $(OUTDIR)/*spec.$(FILEEXT)
+   @sed 's/xit/it/g' $(ASSIGNMENT)/$(TSTFILE) > $(INTDIR)/$(TSTFILE)
```
I will put in a PR for this.  Also, "meetup" has all the tests enabled by default, so I will put in a PR for that too.

**Pull request merged**
