### PR TITLE
TESTS.md: make image links relative

### PR DESCRIPTION
**Pull request by morrme**
See #313

### CODE REVIEW

**Comment by matthewmorgan** [comment]
@morrme Thanks for doing this work.  However, I think the relative pattern that you want in this case is not `./some-file-name.png` but rather `/some-file-name.png` (no dot.)  

This is because the browser needs to resolve the file relative to the site root, where the dot syntax would be for resolving in a filesystem.

I don't have the exercism.io webapp installed locally, but I'm pretty confident you will need to make this change.  Let me know if you think otherwise.  I should be able to find some time to install the app and try your changes locally.

**Comment by morrme** [comment]
When I delete the dot, the image does not render (the left is the current code, the broken link on the right is the result of the change): 
nodot

When I add the dot, it returns.

**Comment by matthewmorgan** [comment]
OK, I think I should try to stand up the exercism UI app locally and see what happens.  Let me try this and I'll report my findings.

**Comment by matthewmorgan** [comment]
OK, I'm having a bear of a time setting the exercism.io UI app up locally.  But, I found a solution that should work for _both_ the local filesystem and the web, EG:

```markdown
img/SolutionExplorer.png
```

No dot, no slash.  I believe this will work bc of the structure.  Shall we try that?

**Comment by matthewmorgan** [comment]
Woohoo!  Thanks @morrme ! 🥇

**Comment by rchavarria** [comment]
Thanks @morrme for this contribution!!

**Pull request merged**
