### PR TITLE
dibs: I will implement exercise <List Ops>

### PR DESCRIPTION
**Pull request by marcCanipel**
I'll work on the List Ops exercise using different others languages, like C# version
https://github.com/exercism/x-common/tree/master/exercises/list-ops

### CODE REVIEW

**Comment by rchavarria** [comment]
Neat!

The link you provided is a link to a folder where canonical tests (tests that should be implemented by all tracks) can be found (https://github.com/exercism/x-common/blob/master/exercises/list-ops/canonical-data.json), so, you could base your tests on that file.

**Comment by marcCanipel** [comment]
Thanks for the link, I look that and I do it.

**Comment by tejasbubane** [comment]
@marcCanipel Are you still working on this?

**Comment by cdlm** [comment]
@marcCanipel's contributions were for a university course that we do in Lille from January to March (discovering development on actual open-source projects from the real world). I hope he comes back to push this one to completion, but it's possible that student life took over and he moved on…

**Comment by marcCanipel** [comment]
Hello, I'm sorry, I haven't see your message. Of course, I have beginning this exercise so, it's normal,  I will finish it but for the moment I don't have lot of time, sorry. May be it's not very difficulte but I need more time to do this.

**Comment by matthewmorgan** [comment]
@marcCanipel thank you for your contribution so far.  I understand you don't have much time right now, but it would be nice to get this PR completed and merged.  Do you mind if someone else continues your work?  

Let us know if that's a problem, otherwise we'll see if we can get this finished for you.

**Comment by marcCanipel** [comment]
I'm alone for this pull Request. I will try to advance on the project this weekend, but on my computer I have problems to push, i don't know why.
I hope to finish the project without leaving it incompleted

**Comment by matthewmorgan** [comment]
@marcCanipel Sorry, but I'm going to close this PR for now.  Please feel free to reopen if you have time to contribute in the future.  Cheers!

**Pull request closed without merging**
